networks:
  jaba_network:
    driver: bridge

services:

  jaba-food-backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaba_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jaba
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      FLYWAY_URL: jdbc:postgresql://postgres:5432/jaba
      FLYWAY_USER: user
      FLYWAY_PASSWORD: password
    networks:
      - jaba_network

  postgres:
    image: postgres:16
    container_name: jaba_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jaba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d jaba" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jaba_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: jaba_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@jaba.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - jaba_network

volumes:
  postgres_data:
  pgadmin_data:
