spring:
  datasource:
    url: jdbc:postgresql://postgres_test:5432/jaba_test
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
