spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jaba}
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: true