spring:
  application:
    name: @project.name@
    version: @project.version@
    description: @project.description@
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/jaba}
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: true
  flyway:
    url: ${FLYWAY_DATABASE_URL:jdbc:postgresql://postgres:5432/jaba}
    user: ${FLYWAY_DATABASE_USER:user}
    password: ${FLYWAY_DATABASE_PASSWORD:password}
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    app.jabafood: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
